---
branches:
  - { name: main, prerelease: false, channel: latest }
  - { name: "rc/*", prerelease: rc, channel: rc }

repositoryUrl: "https://github.com/inference-gateway/adl-cli"
tagFormat: "v${version}"

verifyConditions:
  - "@semantic-release/github"
  - "@semantic-release/git"

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "conventionalcommits"
      releaseRules:
        - { type: "feat", release: "minor" }
        - { type: "impr", release: "patch" }
        - { type: "refactor", release: "patch" }
        - { type: "perf", release: "patch" }
        - { type: "fix", release: "patch" }
        - { type: "ci", release: "patch" }
        - { type: "docs", release: "patch" }
        - { type: "style", release: "patch" }
        - { type: "test", release: "patch" }
        - { type: "build", release: "patch" }
        - { type: "security", release: "patch" }
        - { type: "chore", release: "patch", scope: "!release" }

  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
      presetConfig:
        types:
          - { type: "feat", section: "✨ Features" }
          - { type: "impr", section: "🚀 Improvements" }
          - { type: "refactor", section: "♻️ Improvements" }
          - { type: "perf", section: "⚡️ Improvements" }
          - { type: "fix", section: "🐛 Bug Fixes" }
          - { type: "ci", section: "👷 CI" }
          - { type: "docs", section: "📚 Documentation" }
          - { type: "chore", section: "🔧 Miscellaneous" }
          - { type: "style", section: "🎨 Miscellaneous" }
          - { type: "test", section: "✅ Miscellaneous" }
          - { type: "build", section: "🔨 Miscellaneous" }
          - { type: "security", section: "🔒 Security" }

  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# Changelog\n\nAll notable changes to this project will be documented in this file."
      verifyConditions: true

  - - "@semantic-release/exec"
    - prepareCmd: |
        sed -i "s/VERSION: [0-9]\\+\\.[0-9]\\+\\.[0-9]\\+.*/VERSION: ${nextRelease.version}/" Taskfile.yml

  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - Taskfile.yml
      message: "chore(release): 🔖 ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  - - "@semantic-release/exec"
    - publishCmd: |
        GORELEASER_CURRENT_TAG=v${nextRelease.version} goreleaser release --clean --skip=publish

  - - "@semantic-release/github"
    - assets:
        - CHANGELOG.md
        - path: dist/adl_linux_amd64.tar.gz
          name: adl_linux_amd64.tar.gz
        - path: dist/adl_linux_arm64.tar.gz
          name: adl_linux_arm64.tar.gz
        - path: dist/adl_darwin_amd64.tar.gz
          name: adl_darwin_amd64.tar.gz
        - path: dist/adl_darwin_arm64.tar.gz
          name: adl_darwin_arm64.tar.gz
        - path: dist/checksums.txt
          name: checksums.txt
      releasedLabels: ["released"]
      releaseNameTemplate: "🚀 Version ${nextRelease.version}"
      releaseBodyTemplate: |
        ## What's Changed

        <%= nextRelease.notes %>

        ## 📦 Installation

        ```bash
        curl -fsSL https://raw.githubusercontent.com/inference-gateway/adl-cli/main/install.sh | bash
        ```

        For more installation options, see the [README](https://github.com/inference-gateway/adl-cli#installation).
      successCommentCondition: "false"
      labels:
        - "release"
        - "<%= nextRelease.channel === 'rc' ? 'rc' : '' %>"
