apiVersion: v1
kind: Agent
metadata:
  name: ghcr-example
  description: Example A2A agent using GitHub Container Registry
  version: "1.0.0"
spec:
  capabilities:
    streaming: true
    pushNotifications: false
    stateTransitionHistory: true
  agent:
    provider: openai
    model: gpt-4o
    systemPrompt: |
      You are a helpful A2A agent that uses GitHub Container Registry.
      Your container is pre-built and stored in GHCR.
    maxTokens: 4000
    temperature: 0.7
  skills:
    - id: process
      name: process
      description: Processes data with custom logic
      tags: ["processing", "data"]
      schema:
        type: object
        properties:
          data:
            type: string
            description: The data to process
        required: ["data"]
  server:
    port: 8080
    debug: false
  language:
    go:
      module: github.com/example/ghcr-example
      version: "1.21"
  scm:
    provider: github
    url: "https://github.com/example/ghcr-example"
  deployment:
    type: cloudrun
    cloudrun:
      image:
        registry: ghcr.io
        repository: example/ghcr-example
        tag: latest
        useCloudBuild: false  # Skip Cloud Build since image is pre-built in GHCR
      resources:
        cpu: "2"
        memory: 1Gi
      scaling:
        minInstances: 1
        maxInstances: 50
        concurrency: 500
      service:
        timeout: 1800
        allowUnauthenticated: false
        serviceAccount: ghcr-example@PROJECT_ID.iam.gserviceaccount.com
        executionEnvironment: gen2
      environment:
        LOG_LEVEL: debug
        CACHE_ENABLED: "true"
  sandbox:
    flox:
      enabled: true
