apiVersion: adl.dev/v1
kind: Agent
metadata:
  name: github-app-agent
  description: "Enterprise agent with GitHub App CD integration"
  version: "0.1.0"
spec:
  capabilities:
    streaming: true
    pushNotifications: true
    stateTransitionHistory: true
  card:
    protocolVersion: "0.3.0"
    preferredTransport: "JSONRPC"
    defaultInputModes: ["text"]
    defaultOutputModes: ["text"]
    url: "https://my-agent.example.com:8443"
    documentationUrl: "https://github.com/company/github-app-agent/docs"
    iconUrl: "https://github.com/company/github-app-agent/icon.png"
  agent:
    provider: openai
    model: gpt-4
    systemPrompt: |
      You are an enterprise assistant with enhanced security and audit capabilities.
      Always prioritize security, accuracy, and compliance in your responses.
      Log all interactions for audit purposes.
    maxTokens: 8192
    temperature: 0.3
  skills:
    - id: enterprise_query
      name: enterprise_query
      description: "Query enterprise data with proper authentication and audit logging"
      tags: ["enterprise", "query", "data", "audit"]
      schema:
        type: object
        properties:
          query:
            type: string
            description: "Query to execute"
          data_source:
            type: string
            description: "Data source to query"
            enum: ["database", "api", "document_store"]
          audit_context:
            type: object
            properties:
              user_id:
                type: string
                description: "User ID for audit trail"
              session_id:
                type: string
                description: "Session ID for audit trail"
            required: [user_id, session_id]
        required: [query, data_source, audit_context]
    - id: compliance_check
      name: compliance_check
      description: "Perform compliance checks on data or operations"
      tags: ["compliance", "security", "audit"]
      schema:
        type: object
        properties:
          operation:
            type: string
            description: "Operation to check for compliance"
          data_classification:
            type: string
            description: "Data classification level"
            enum: ["public", "internal", "confidential", "restricted"]
          compliance_framework:
            type: string
            description: "Compliance framework to validate against"
            enum: ["gdpr", "hipaa", "sox", "pci_dss"]
        required: [operation, data_classification, compliance_framework]
  server:
    port: 8443
    debug: false
    auth:
      enabled: true
  language:
    go:
      module: "github.com/company/github-app-agent"
      version: "1.24"
  scm:
    provider: github
    url: "https://github.com/company/github-app-agent"
    github_app: true
  sandbox:
    flox:
      enabled: true
    devcontainer:
      enabled: false