apiVersion: adl.dev/v1
kind: Agent
metadata:
  name: go-agent
  description: "Minimal agent with basic functionality"
  version: "0.1.0"
spec:
  capabilities:
    streaming: true
    pushNotifications: true
    stateTransitionHistory: true
  agent:
    provider: deepseek
    model: deepseek-chat
    systemPrompt: |
      You are are an helpful assistant.
      Always prioritize security, accuracy, and compliance in your responses.
      Log all interactions for audit purposes.
    maxTokens: 8192
    temperature: 0.3
  skills:
    - id: query_database
      name: query_database
      description: "Query the company database with proper authentication"
      tags: ["database", "query", "data"]
      schema:
        type: object
        properties:
          query:
            type: string
            description: "SQL query to execute"
          table:
            type: string
            description: "Table name to query"
          limit:
            type: integer
            description: "Maximum number of results"
            maximum: 1000
        required: [query, table]
    - id: send_notification
      name: send_notification
      description: "Send notifications to users or teams"
      tags: ["notification", "communication", "alert"]
      schema:
        type: object
        properties:
          recipient:
            type: string
            description: "Recipient email or team name"
          message:
            type: string
            description: "Notification message"
          priority:
            type: string
            description: "Priority level"
            enum: ["low", "medium", "high", "critical"]
          channel:
            type: string
            description: "Notification channel"
            enum: ["email", "slack", "teams", "webhook"]
        required: [recipient, message, priority, channel]
    - id: generate_report
      name: generate_report
      description: "Generate business reports based on data analysis"
      tags: ["report", "analytics", "business"]
      schema:
        type: object
        properties:
          report_type:
            type: string
            description: "Type of report to generate"
            enum: ["sales", "performance", "compliance", "security"]
          date_range:
            type: object
            properties:
              start:
                type: string
                format: date
              end:
                type: string
                format: date
          format:
            type: string
            description: "Output format"
            enum: ["pdf", "excel", "json", "html"]
        required: [report_type, date_range, format]
  server:
    port: 8443
    debug: false
    auth:
      enabled: true
  language:
    go:
      module: "github.com/company/go-agent"
      version: "1.24"
  scm:
    provider: github
    url: "https://github.com/company/go-agent"
  sandbox:
    flox:
      enabled: true
    devcontainer:
      enabled: false
  # hooks:
  #   post:
  #     - "go mod tidy"
  #     - "go generate ./..."