package templates

import (
	"fmt"
	"time"
)

// getGeneratedFileHeader returns a comment header for generated files
func getGeneratedFileHeader(fileType, cliVersion string, generatedAt time.Time) string {
	switch fileType {
	case "go":
		return fmt.Sprintf(`// Code generated by ADL CLI v%s at %s. DO NOT EDIT.
// This file was automatically generated from an Agent Definition Language (ADL) file.
// To regenerate this file, run: adl generate
//
// For more information about ADL CLI, visit: https://github.com/inference-gateway/adl-cli

`, cliVersion, generatedAt.Format("2006-01-02 15:04:05 UTC"))
	case "rust":
		return fmt.Sprintf(`// Code generated by ADL CLI v%s at %s. DO NOT EDIT.
// This file was automatically generated from an Agent Definition Language (ADL) file.
// To regenerate this file, run: adl generate
//
// For more information about ADL CLI, visit: https://github.com/inference-gateway/adl-cli

`, cliVersion, generatedAt.Format("2006-01-02 15:04:05 UTC"))
	case "yaml", "yml":
		return fmt.Sprintf(`# Generated by ADL CLI v%s at %s. DO NOT EDIT.
# This file was automatically generated from an Agent Definition Language (ADL) file.
# To regenerate this file, run: adl generate
#
# For more information about ADL CLI, visit: https://github.com/inference-gateway/adl-cli

`, cliVersion, generatedAt.Format("2006-01-02 15:04:05 UTC"))
	case "dockerfile":
		return fmt.Sprintf(`# Generated by ADL CLI v%s at %s. DO NOT EDIT.
# This file was automatically generated from an Agent Definition Language (ADL) file.
# To regenerate this file, run: adl generate
#
# For more information about ADL CLI, visit: https://github.com/inference-gateway/adl-cli

`, cliVersion, generatedAt.Format("2006-01-02 15:04:05 UTC"))
	case "taskfile":
		return fmt.Sprintf(`# Generated by ADL CLI v%s at %s. DO NOT EDIT.
# This file was automatically generated from an Agent Definition Language (ADL) file.
# To regenerate this file, run: adl generate
#
# For more information about ADL CLI, visit: https://github.com/inference-gateway/adl-cli

`, cliVersion, generatedAt.Format("2006-01-02 15:04:05 UTC"))
	default:
		return ""
	}
}

// gitattributesGoTemplate provides Git attributes for Go projects
const gitattributesGoTemplate = `# Generated files by ADL CLI
# These files are automatically generated and should not be manually edited

# Core Go generated files
main.go linguist-generated=true
go.mod linguist-generated=true
go.sum linguist-generated=true

# Build and deployment files
Dockerfile linguist-generated=true
Taskfile.yml linguist-generated=true
.gitignore linguist-generated=true

# Kubernetes manifests
k8s/*.yaml linguist-generated=true
k8s/*.yml linguist-generated=true

# Agent capabilities
.well-known/agent.json linguist-generated=true

# Documentation (partially generated)
README.md linguist-documentation=true

# Preserve line endings for generated files
*.go text eol=lf
*.yaml text eol=lf
*.yml text eol=lf
*.json text eol=lf
*.md text eol=lf
Dockerfile text eol=lf
Taskfile.yml text eol=lf
`

// gitattributesRustTemplate provides Git attributes for Rust projects
const gitattributesRustTemplate = `# Generated files by ADL CLI
# These files are automatically generated and should not be manually edited

# Core Rust generated files
src/main.rs linguist-generated=true
Cargo.toml linguist-generated=true
Cargo.lock linguist-generated=true

# Build and deployment files
Dockerfile linguist-generated=true
Taskfile.yml linguist-generated=true
.gitignore linguist-generated=true

# Kubernetes manifests
k8s/*.yaml linguist-generated=true
k8s/*.yml linguist-generated=true

# Agent capabilities
.well-known/agent.json linguist-generated=true

# Documentation (partially generated)
README.md linguist-documentation=true

# Preserve line endings for generated files
*.rs text eol=lf
*.yaml text eol=lf
*.yml text eol=lf
*.json text eol=lf
*.md text eol=lf
Dockerfile text eol=lf
Taskfile.yml text eol=lf
`
