package templates

import (
	"fmt"
	"strings"
	"time"
)

// GetGeneratedFileHeader returns the appropriate header for generated files
func GetGeneratedFileHeader(fileType string, cliVersion string, generatedAt time.Time) string {
	headerText := fmt.Sprintf(`Code generated by ADL CLI v%s. DO NOT EDIT.
This file was automatically generated from an ADL (Agent Definition Language) specification.
Manual changes to this file may be overwritten during regeneration.`, cliVersion)

	switch fileType {
	case "go", "rust", "typescript", "javascript":
		return "// " + strings.ReplaceAll(headerText, "\n", "\n// ") + "\n\n"
	case "yaml", "dockerfile", "taskfile":
		return "# " + strings.ReplaceAll(headerText, "\n", "\n# ") + "\n\n"
	default:
		return ""
	}
}
