// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

// JSON Schema for Agent Definition Language manifests (apiVersion
// adl.inference-gateway.com/v1).
type ADL struct {
	// APIVersion corresponds to the JSON schema field "apiVersion".
	APIVersion string `json:"apiVersion" yaml:"apiVersion" mapstructure:"apiVersion"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Metadata corresponds to the JSON schema field "metadata".
	Metadata Metadata `json:"metadata" yaml:"metadata" mapstructure:"metadata"`

	// Spec corresponds to the JSON schema field "spec".
	Spec Spec `json:"spec" yaml:"spec" mapstructure:"spec"`
}

// Configures AI-assistant integration for the agent project: generation of
// AI-assistant documentation (CLAUDE.md, AGENTS.md) and provisioning of
// coding-agent orchestrators inside sandbox environments.
type AIConfig struct {
	// Orchestrators corresponds to the JSON schema field "orchestrators".
	Orchestrators *OrchestratorsConfig `json:"orchestrators,omitempty,omitzero" yaml:"orchestrators,omitempty" mapstructure:"orchestrators,omitempty"`
}

type Agent struct {
	// MaxTokens corresponds to the JSON schema field "maxTokens".
	MaxTokens int `json:"maxTokens,omitempty,omitzero" yaml:"maxTokens,omitempty" mapstructure:"maxTokens,omitempty"`

	// MCP (Model Context Protocol) servers the agent connects to at runtime to
	// discover and call external tools and capabilities, in addition to the locally
	// generated 'spec.tools'. Only meaningful for an LLM-backed agent: A2A itself
	// does not require an LLM, so this lives under 'spec.agent'. Each entry declares
	// a transport plus the connection details for that transport.
	Mcps []MCP `json:"mcps,omitempty,omitzero" yaml:"mcps,omitempty" mapstructure:"mcps,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model string `json:"model,omitempty,omitzero" yaml:"model,omitempty" mapstructure:"model,omitempty"`

	// Provider corresponds to the JSON schema field "provider".
	Provider AgentProvider `json:"provider,omitempty,omitzero" yaml:"provider,omitempty" mapstructure:"provider,omitempty"`

	// SystemPrompt corresponds to the JSON schema field "systemPrompt".
	SystemPrompt string `json:"systemPrompt,omitempty,omitzero" yaml:"systemPrompt,omitempty" mapstructure:"systemPrompt,omitempty"`

	// Temperature corresponds to the JSON schema field "temperature".
	Temperature float64 `json:"temperature,omitempty,omitzero" yaml:"temperature,omitempty" mapstructure:"temperature,omitempty"`
}

type AgentProvider string

const AgentProviderAnthropic AgentProvider = "anthropic"
const AgentProviderBlank AgentProvider = ""
const AgentProviderCloudflare AgentProvider = "cloudflare"
const AgentProviderCohere AgentProvider = "cohere"
const AgentProviderDeepseek AgentProvider = "deepseek"
const AgentProviderGoogle AgentProvider = "google"
const AgentProviderGroq AgentProvider = "groq"
const AgentProviderMistral AgentProvider = "mistral"
const AgentProviderMoonshot AgentProvider = "moonshot"
const AgentProviderOllama AgentProvider = "ollama"
const AgentProviderOllamaCloud AgentProvider = "ollama_cloud"
const AgentProviderOpenai AgentProvider = "openai"

type ArtifactsConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type AuthConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty,omitzero" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`
}

type Capabilities struct {
	// PushNotifications corresponds to the JSON schema field "pushNotifications".
	PushNotifications bool `json:"pushNotifications" yaml:"pushNotifications" mapstructure:"pushNotifications"`

	// StateTransitionHistory corresponds to the JSON schema field
	// "stateTransitionHistory".
	StateTransitionHistory bool `json:"stateTransitionHistory" yaml:"stateTransitionHistory" mapstructure:"stateTransitionHistory"`

	// Streaming corresponds to the JSON schema field "streaming".
	Streaming bool `json:"streaming" yaml:"streaming" mapstructure:"streaming"`
}

type Card struct {
	// DefaultInputModes corresponds to the JSON schema field "defaultInputModes".
	DefaultInputModes []string `json:"defaultInputModes,omitempty,omitzero" yaml:"defaultInputModes,omitempty" mapstructure:"defaultInputModes,omitempty"`

	// DefaultOutputModes corresponds to the JSON schema field "defaultOutputModes".
	DefaultOutputModes []string `json:"defaultOutputModes,omitempty,omitzero" yaml:"defaultOutputModes,omitempty" mapstructure:"defaultOutputModes,omitempty"`

	// DocumentationURL corresponds to the JSON schema field "documentationUrl".
	DocumentationURL string `json:"documentationUrl,omitempty,omitzero" yaml:"documentationUrl,omitempty" mapstructure:"documentationUrl,omitempty"`

	// IconURL corresponds to the JSON schema field "iconUrl".
	IconURL string `json:"iconUrl,omitempty,omitzero" yaml:"iconUrl,omitempty" mapstructure:"iconUrl,omitempty"`

	// PreferredTransport corresponds to the JSON schema field "preferredTransport".
	PreferredTransport string `json:"preferredTransport,omitempty,omitzero" yaml:"preferredTransport,omitempty" mapstructure:"preferredTransport,omitempty"`

	// ProtocolVersion corresponds to the JSON schema field "protocolVersion".
	ProtocolVersion string `json:"protocolVersion,omitempty,omitzero" yaml:"protocolVersion,omitempty" mapstructure:"protocolVersion,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

// Provision Anthropic's Claude Code coding agent inside the sandbox.
type ClaudeCodeConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type CloudRunConfig struct {
	// Environment corresponds to the JSON schema field "environment".
	Environment CloudRunConfigEnvironment `json:"environment,omitempty,omitzero" yaml:"environment,omitempty" mapstructure:"environment,omitempty"`

	// Image corresponds to the JSON schema field "image".
	Image *ImageConfig `json:"image,omitempty,omitzero" yaml:"image,omitempty" mapstructure:"image,omitempty"`

	// Resources corresponds to the JSON schema field "resources".
	Resources *ResourcesConfig `json:"resources,omitempty,omitzero" yaml:"resources,omitempty" mapstructure:"resources,omitempty"`

	// Scaling corresponds to the JSON schema field "scaling".
	Scaling *ScalingConfig `json:"scaling,omitempty,omitzero" yaml:"scaling,omitempty" mapstructure:"scaling,omitempty"`

	// Service corresponds to the JSON schema field "service".
	Service *ServiceConfig `json:"service,omitempty,omitzero" yaml:"service,omitempty" mapstructure:"service,omitempty"`
}

type CloudRunConfigEnvironment map[string]string

// Configuration for deploying to Cloudflare Workers. Like vercel and unlike
// kubernetes/cloudrun, Workers deploy from source via wrangler rather than a
// prebuilt container image, so there is no image sub-block. This models Workers
// (the server/serverless product, the right target for an A2A agent server), not
// Pages. Consumers (e.g. adl-cli) translate this block into wrangler configuration
// (wrangler.toml / wrangler.jsonc).
type CloudflareConfig struct {
	// Cloudflare account ID that owns the Worker. Prefer a ${VAR} placeholder over
	// inlining the value.
	AccountID string `json:"accountId,omitempty,omitzero" yaml:"accountId,omitempty" mapstructure:"accountId,omitempty"`

	// Workers runtime compatibility date in YYYY-MM-DD form (e.g. "2025-01-01").
	// Effectively required by wrangler; when omitted the generator supplies a
	// default. See
	// https://developers.cloudflare.com/workers/configuration/compatibility-dates/.
	CompatibilityDate string `json:"compatibilityDate,omitempty,omitzero" yaml:"compatibilityDate,omitempty" mapstructure:"compatibilityDate,omitempty"`

	// Workers runtime compatibility flags (e.g. "nodejs_compat" to enable Node.js API
	// compatibility). Workers always run on the V8-isolate edge runtime, so Node API
	// needs are met via flags rather than a runtime enum.
	CompatibilityFlags []string `json:"compatibilityFlags,omitempty,omitzero" yaml:"compatibilityFlags,omitempty" mapstructure:"compatibilityFlags,omitempty"`

	// Plain-text environment variables (wrangler "vars") injected into the Worker.
	// Values can use the ${VAR} placeholder convention; never inline a real secret
	// here - Cloudflare secrets are set out-of-band with "wrangler secret put". See
	// docs/reference/secrets.md.
	Environment CloudflareConfigEnvironment `json:"environment,omitempty,omitzero" yaml:"environment,omitempty" mapstructure:"environment,omitempty"`

	// Worker name - the script name registered with Cloudflare (e.g.
	// "customer-support-agent"). Surfaces as the wrangler "name" field.
	Name string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Custom routes / domains the Worker is served on (e.g. "agent.example.com/*").
	// Omit to rely on the workers.dev subdomain.
	Routes []string `json:"routes,omitempty,omitzero" yaml:"routes,omitempty" mapstructure:"routes,omitempty"`

	// Whether the Worker is exposed on its *.workers.dev subdomain. Set false when
	// serving exclusively via custom routes.
	WorkersDev bool `json:"workersDev,omitempty,omitzero" yaml:"workersDev,omitempty" mapstructure:"workersDev,omitempty"`
}

// Plain-text environment variables (wrangler "vars") injected into the Worker.
// Values can use the ${VAR} placeholder convention; never inline a real secret
// here - Cloudflare secrets are set out-of-band with "wrangler secret put". See
// docs/reference/secrets.md.
type CloudflareConfigEnvironment map[string]string

// Provision OpenAI's Codex coding agent inside the sandbox.
type CodexConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type DeploymentConfig struct {
	// Cloudflare corresponds to the JSON schema field "cloudflare".
	Cloudflare *CloudflareConfig `json:"cloudflare,omitempty,omitzero" yaml:"cloudflare,omitempty" mapstructure:"cloudflare,omitempty"`

	// CloudRun corresponds to the JSON schema field "cloudrun".
	CloudRun *CloudRunConfig `json:"cloudrun,omitempty,omitzero" yaml:"cloudrun,omitempty" mapstructure:"cloudrun,omitempty"`

	// Kubernetes corresponds to the JSON schema field "kubernetes".
	Kubernetes *KubernetesConfig `json:"kubernetes,omitempty,omitzero" yaml:"kubernetes,omitempty" mapstructure:"kubernetes,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type DeploymentConfigType `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`

	// Vercel corresponds to the JSON schema field "vercel".
	Vercel *VercelConfig `json:"vercel,omitempty,omitzero" yaml:"vercel,omitempty" mapstructure:"vercel,omitempty"`
}

type DeploymentConfigType string

const DeploymentConfigTypeCloudRun DeploymentConfigType = "cloudrun"
const DeploymentConfigTypeCloudflare DeploymentConfigType = "cloudflare"
const DeploymentConfigTypeKubernetes DeploymentConfigType = "kubernetes"
const DeploymentConfigTypeVercel DeploymentConfigType = "vercel"

type DevContainerConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

// Local development experience for the agent: sandboxed dev environments (flox,
// devcontainer, dockerCompose), AI-assistant integration (CLAUDE.md/AGENTS.md
// generation, claude-code provisioning), and extra sandbox-level dependencies
// (deps) for tools that don't belong to any single language's package manager
// (e.g. deno, kubectl, terraform).
type DevelopmentConfig struct {
	// AI corresponds to the JSON schema field "ai".
	AI *AIConfig `json:"ai,omitempty,omitzero" yaml:"ai,omitempty" mapstructure:"ai,omitempty"`

	// Extra packages to install into the development sandbox (flox, devcontainer,
	// dockerCompose) on top of whatever the generator pulls in by default. Use this
	// for cross-cutting tools that aren't tied to one of the project's languages -
	// e.g. 'deno@2.1.4', 'kubectl@1.31.0', 'terraform@1.9.5'. Each entry follows the
	// '<package>@<version>' form; consumers are responsible for resolving the package
	// against the sandbox's native package source (Nixpkgs for flox, apt/apk/feature
	// for devcontainer, image layers for dockerCompose).
	Deps []string `json:"deps,omitempty,omitzero" yaml:"deps,omitempty" mapstructure:"deps,omitempty"`

	// Sandbox corresponds to the JSON schema field "sandbox".
	Sandbox *SandboxConfig `json:"sandbox,omitempty,omitzero" yaml:"sandbox,omitempty" mapstructure:"sandbox,omitempty"`
}

type DockerComposeConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type FloxConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

// Provision Google's Gemini coding agent inside the sandbox.
type GeminiConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type GoConfig struct {
	// Module corresponds to the JSON schema field "module".
	Module string `json:"module" yaml:"module" mapstructure:"module"`

	// Vendor corresponds to the JSON schema field "vendor".
	Vendor *VendorConfig `json:"vendor,omitempty,omitzero" yaml:"vendor,omitempty" mapstructure:"vendor,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

type Hooks struct {
	// Post corresponds to the JSON schema field "post".
	Post []string `json:"post,omitempty,omitzero" yaml:"post,omitempty" mapstructure:"post,omitempty"`
}

type ImageConfig struct {
	// Registry corresponds to the JSON schema field "registry".
	Registry string `json:"registry,omitempty,omitzero" yaml:"registry,omitempty" mapstructure:"registry,omitempty"`

	// Repository corresponds to the JSON schema field "repository".
	Repository string `json:"repository,omitempty,omitzero" yaml:"repository,omitempty" mapstructure:"repository,omitempty"`

	// Tag corresponds to the JSON schema field "tag".
	Tag string `json:"tag,omitempty,omitzero" yaml:"tag,omitempty" mapstructure:"tag,omitempty"`

	// UseCloudBuild corresponds to the JSON schema field "useCloudBuild".
	UseCloudBuild bool `json:"useCloudBuild,omitempty,omitzero" yaml:"useCloudBuild,omitempty" mapstructure:"useCloudBuild,omitempty"`
}

// Provision the Inference Gateway 'infer' coding agent inside the sandbox.
type InferConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type KubernetesConfig struct {
	// Image corresponds to the JSON schema field "image".
	Image *ImageConfig `json:"image,omitempty,omitzero" yaml:"image,omitempty" mapstructure:"image,omitempty"`
}

type Language struct {
	// Go corresponds to the JSON schema field "go".
	Go *GoConfig `json:"go,omitempty,omitzero" yaml:"go,omitempty" mapstructure:"go,omitempty"`

	// Rust corresponds to the JSON schema field "rust".
	Rust *RustConfig `json:"rust,omitempty,omitzero" yaml:"rust,omitempty" mapstructure:"rust,omitempty"`

	// TypeScript corresponds to the JSON schema field "typescript".
	TypeScript *TypeScriptConfig `json:"typescript,omitempty,omitzero" yaml:"typescript,omitempty" mapstructure:"typescript,omitempty"`
}

// A single MCP (Model Context Protocol) server the agent can connect to. 'stdio'
// launches a local subprocess and talks over stdin/stdout (use 'command', 'args',
// and 'env'); 'http' and 'sse' connect to a remote endpoint (use 'url' and
// 'headers'). Connection details that do not apply to the chosen transport are
// simply omitted; the schema does not constrain which combination is present so
// consumers can stay lenient.
type MCP struct {
	// Arguments passed to 'command' when launching a 'stdio' server.
	Args []string `json:"args,omitempty,omitzero" yaml:"args,omitempty" mapstructure:"args,omitempty"`

	// Executable to launch for a 'stdio' server (e.g. 'npx', 'uvx', 'docker').
	// Ignored by remote transports.
	Command string `json:"command,omitempty,omitzero" yaml:"command,omitempty" mapstructure:"command,omitempty"`

	// Environment variables set when launching a 'stdio' server (e.g. API keys or
	// tokens the server needs).
	Env MCPEnv `json:"env,omitempty,omitzero" yaml:"env,omitempty" mapstructure:"env,omitempty"`

	// Extra HTTP headers sent when connecting to an 'http' or 'sse' server (e.g.
	// 'Authorization').
	Headers MCPHeaders `json:"headers,omitempty,omitzero" yaml:"headers,omitempty" mapstructure:"headers,omitempty"`

	// Identifier for the MCP server, unique within the agent. Consumers typically use
	// it to namespace the tools the server exposes.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// How the agent connects to the MCP server. New transports may be added in future
	// minor versions; consumers should be lenient about unknown values.
	Transport MCPTransport `json:"transport" yaml:"transport" mapstructure:"transport"`

	// Endpoint URL for an 'http' or 'sse' server. Ignored by the 'stdio' transport.
	URL string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

// Environment variables set when launching a 'stdio' server (e.g. API keys or
// tokens the server needs).
type MCPEnv map[string]string

// Extra HTTP headers sent when connecting to an 'http' or 'sse' server (e.g.
// 'Authorization').
type MCPHeaders map[string]string

type MCPTransport string

const MCPTransportHttp MCPTransport = "http"
const MCPTransportSse MCPTransport = "sse"
const MCPTransportStdio MCPTransport = "stdio"

type Metadata struct {
	// Author of the agent. Optional; when provided, 'name' is required. 'email' and
	// 'url' are optional contact fields.
	Author *MetadataAuthor `json:"author,omitempty,omitzero" yaml:"author,omitempty" mapstructure:"author,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// SPDX identifier under which the agent is distributed, or "Proprietary" for
	// closed-source agents. Mirrors the enum used for Skill.license so the same
	// accepted set applies at the agent level. New identifiers may be added in future
	// minor versions of the schema.
	License MetadataLicense `json:"license,omitempty,omitzero" yaml:"license,omitempty" mapstructure:"license,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Discoverability tags for the agent (e.g. 'calendar', 'automation'). Consumers
	// may merge these with tool- and skill-level tags when indexing.
	Tags []string `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

// Author of the agent. Optional; when provided, 'name' is required. 'email' and
// 'url' are optional contact fields.
type MetadataAuthor struct {
	// Email corresponds to the JSON schema field "email".
	Email string `json:"email,omitempty,omitzero" yaml:"email,omitempty" mapstructure:"email,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// URL corresponds to the JSON schema field "url".
	URL string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type MetadataLicense string

const MetadataLicenseApache20 MetadataLicense = "Apache-2.0"
const MetadataLicenseBSD2Clause MetadataLicense = "BSD-2-Clause"
const MetadataLicenseBSD3Clause MetadataLicense = "BSD-3-Clause"
const MetadataLicenseCC010 MetadataLicense = "CC0-1.0"
const MetadataLicenseCCBY40 MetadataLicense = "CC-BY-4.0"
const MetadataLicenseCCBYSA40 MetadataLicense = "CC-BY-SA-4.0"
const MetadataLicenseGPL20 MetadataLicense = "GPL-2.0"
const MetadataLicenseGPL30 MetadataLicense = "GPL-3.0"
const MetadataLicenseISC MetadataLicense = "ISC"
const MetadataLicenseLGPL21 MetadataLicense = "LGPL-2.1"
const MetadataLicenseLGPL30 MetadataLicense = "LGPL-3.0"
const MetadataLicenseMIT MetadataLicense = "MIT"
const MetadataLicenseMPL20 MetadataLicense = "MPL-2.0"
const MetadataLicenseProprietary MetadataLicense = "Proprietary"
const MetadataLicenseUnlicense MetadataLicense = "Unlicense"

// Provision the OpenCode coding agent inside the sandbox.
type OpenCodeConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

// Coding-agent orchestrators to provision inside the sandbox (Claude Code, Codex,
// Gemini, OpenCode, Infer, ...). Each orchestrator is toggled independently via
// its own subsection; by default every orchestrator is disabled.
type OrchestratorsConfig struct {
	// Claudecode corresponds to the JSON schema field "claudecode".
	Claudecode *ClaudeCodeConfig `json:"claudecode,omitempty,omitzero" yaml:"claudecode,omitempty" mapstructure:"claudecode,omitempty"`

	// Codex corresponds to the JSON schema field "codex".
	Codex *CodexConfig `json:"codex,omitempty,omitzero" yaml:"codex,omitempty" mapstructure:"codex,omitempty"`

	// Gemini corresponds to the JSON schema field "gemini".
	Gemini *GeminiConfig `json:"gemini,omitempty,omitzero" yaml:"gemini,omitempty" mapstructure:"gemini,omitempty"`

	// Infer corresponds to the JSON schema field "infer".
	Infer *InferConfig `json:"infer,omitempty,omitzero" yaml:"infer,omitempty" mapstructure:"infer,omitempty"`

	// Opencode corresponds to the JSON schema field "opencode".
	Opencode *OpenCodeConfig `json:"opencode,omitempty,omitzero" yaml:"opencode,omitempty" mapstructure:"opencode,omitempty"`
}

type ResourcesConfig struct {
	// CPU corresponds to the JSON schema field "cpu".
	CPU string `json:"cpu,omitempty,omitzero" yaml:"cpu,omitempty" mapstructure:"cpu,omitempty"`

	// Memory corresponds to the JSON schema field "memory".
	Memory string `json:"memory,omitempty,omitzero" yaml:"memory,omitempty" mapstructure:"memory,omitempty"`
}

type RustConfig struct {
	// Edition corresponds to the JSON schema field "edition".
	Edition string `json:"edition" yaml:"edition" mapstructure:"edition"`

	// Features corresponds to the JSON schema field "features".
	Features []string `json:"features,omitempty,omitzero" yaml:"features,omitempty" mapstructure:"features,omitempty"`

	// PackageName corresponds to the JSON schema field "packageName".
	PackageName string `json:"packageName" yaml:"packageName" mapstructure:"packageName"`

	// Vendor corresponds to the JSON schema field "vendor".
	Vendor *VendorConfig `json:"vendor,omitempty,omitzero" yaml:"vendor,omitempty" mapstructure:"vendor,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

type SCM struct {
	// CD corresponds to the JSON schema field "cd".
	CD bool `json:"cd,omitempty,omitzero" yaml:"cd,omitempty" mapstructure:"cd,omitempty"`

	// CI corresponds to the JSON schema field "ci".
	CI bool `json:"ci,omitempty,omitzero" yaml:"ci,omitempty" mapstructure:"ci,omitempty"`

	// Dependabot corresponds to the JSON schema field "dependabot".
	Dependabot bool `json:"dependabot,omitempty,omitzero" yaml:"dependabot,omitempty" mapstructure:"dependabot,omitempty"`

	// GithubApp corresponds to the JSON schema field "github_app".
	GithubApp bool `json:"github_app,omitempty,omitzero" yaml:"github_app,omitempty" mapstructure:"github_app,omitempty"`

	// IssueTemplates corresponds to the JSON schema field "issue_templates".
	IssueTemplates bool `json:"issue_templates,omitempty,omitzero" yaml:"issue_templates,omitempty" mapstructure:"issue_templates,omitempty"`

	// Provider corresponds to the JSON schema field "provider".
	Provider SCMProvider `json:"provider,omitempty,omitzero" yaml:"provider,omitempty" mapstructure:"provider,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type SCMProvider string

const SCMProviderBitbucket SCMProvider = "bitbucket"
const SCMProviderGithub SCMProvider = "github"
const SCMProviderGitlab SCMProvider = "gitlab"

// Reproducible development environments. flox, devcontainer, and dockerCompose are
// alternative ways to package the same sandbox; pick what suits the team.
type SandboxConfig struct {
	// DevContainer corresponds to the JSON schema field "devcontainer".
	DevContainer *DevContainerConfig `json:"devcontainer,omitempty,omitzero" yaml:"devcontainer,omitempty" mapstructure:"devcontainer,omitempty"`

	// DockerCompose corresponds to the JSON schema field "dockerCompose".
	DockerCompose *DockerComposeConfig `json:"dockerCompose,omitempty,omitzero" yaml:"dockerCompose,omitempty" mapstructure:"dockerCompose,omitempty"`

	// Flox corresponds to the JSON schema field "flox".
	Flox *FloxConfig `json:"flox,omitempty,omitzero" yaml:"flox,omitempty" mapstructure:"flox,omitempty"`
}

type ScalingConfig struct {
	// Concurrency corresponds to the JSON schema field "concurrency".
	Concurrency int `json:"concurrency,omitempty,omitzero" yaml:"concurrency,omitempty" mapstructure:"concurrency,omitempty"`

	// MaxInstances corresponds to the JSON schema field "maxInstances".
	MaxInstances int `json:"maxInstances,omitempty,omitzero" yaml:"maxInstances,omitempty" mapstructure:"maxInstances,omitempty"`

	// MinInstances corresponds to the JSON schema field "minInstances".
	MinInstances int `json:"minInstances,omitempty,omitzero" yaml:"minInstances,omitempty" mapstructure:"minInstances,omitempty"`
}

type Server struct {
	// Auth corresponds to the JSON schema field "auth".
	Auth *AuthConfig `json:"auth,omitempty,omitzero" yaml:"auth,omitempty" mapstructure:"auth,omitempty"`

	// Debug corresponds to the JSON schema field "debug".
	Debug bool `json:"debug,omitempty,omitzero" yaml:"debug,omitempty" mapstructure:"debug,omitempty"`

	// Port corresponds to the JSON schema field "port".
	Port int `json:"port" yaml:"port" mapstructure:"port"`

	// Scheme corresponds to the JSON schema field "scheme".
	Scheme string `json:"scheme,omitempty,omitzero" yaml:"scheme,omitempty" mapstructure:"scheme,omitempty"`
}

type Service struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Factory corresponds to the JSON schema field "factory".
	Factory string `json:"factory" yaml:"factory" mapstructure:"factory"`

	// Interface corresponds to the JSON schema field "interface".
	Interface string `json:"interface" yaml:"interface" mapstructure:"interface"`

	// Type corresponds to the JSON schema field "type".
	Type ServiceType `json:"type" yaml:"type" mapstructure:"type"`
}

type ServiceConfig struct {
	// AllowUnauthenticated corresponds to the JSON schema field
	// "allowUnauthenticated".
	AllowUnauthenticated bool `json:"allowUnauthenticated,omitempty,omitzero" yaml:"allowUnauthenticated,omitempty" mapstructure:"allowUnauthenticated,omitempty"`

	// ExecutionEnvironment corresponds to the JSON schema field
	// "executionEnvironment".
	ExecutionEnvironment string `json:"executionEnvironment,omitempty,omitzero" yaml:"executionEnvironment,omitempty" mapstructure:"executionEnvironment,omitempty"`

	// ServiceAccount corresponds to the JSON schema field "serviceAccount".
	ServiceAccount string `json:"serviceAccount,omitempty,omitzero" yaml:"serviceAccount,omitempty" mapstructure:"serviceAccount,omitempty"`

	// Timeout corresponds to the JSON schema field "timeout".
	Timeout int `json:"timeout,omitempty,omitzero" yaml:"timeout,omitempty" mapstructure:"timeout,omitempty"`
}

type ServiceType string

const ServiceTypeClient ServiceType = "client"
const ServiceTypeMiddleware ServiceType = "middleware"
const ServiceTypeRepository ServiceType = "repository"
const ServiceTypeService ServiceType = "service"

// Markdown playbook the agent can discover and load on demand at runtime. Each
// skill's metadata (name and description) is advertised to the model at startup;
// the SKILL.md body is read lazily when the model invokes the skill. Pulled from
// the skills registry or scaffolded blank with bare: true.
type Skill struct {
	// Bare corresponds to the JSON schema field "bare".
	Bare bool `json:"bare,omitempty,omitzero" yaml:"bare,omitempty" mapstructure:"bare,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id" mapstructure:"id"`

	// License under which the skill is distributed. Must be one of the accepted SPDX
	// license identifiers, or "Proprietary" for closed-source skills. Consumers
	// should mirror this value in the SKILL.md frontmatter so the licence travels
	// with the playbook; shipping a separate LICENSE file alongside SKILL.md is
	// optional and not enforced by the schema. New identifiers may be added in future
	// minor versions of the schema.
	License SkillLicense `json:"license,omitempty,omitzero" yaml:"license,omitempty" mapstructure:"license,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Source corresponds to the JSON schema field "source".
	Source string `json:"source,omitempty,omitzero" yaml:"source,omitempty" mapstructure:"source,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version,omitempty,omitzero" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

type SkillLicense string

const SkillLicenseApache20 SkillLicense = "Apache-2.0"
const SkillLicenseBSD2Clause SkillLicense = "BSD-2-Clause"
const SkillLicenseBSD3Clause SkillLicense = "BSD-3-Clause"
const SkillLicenseCC010 SkillLicense = "CC0-1.0"
const SkillLicenseCCBY40 SkillLicense = "CC-BY-4.0"
const SkillLicenseCCBYSA40 SkillLicense = "CC-BY-SA-4.0"
const SkillLicenseGPL20 SkillLicense = "GPL-2.0"
const SkillLicenseGPL30 SkillLicense = "GPL-3.0"
const SkillLicenseISC SkillLicense = "ISC"
const SkillLicenseLGPL21 SkillLicense = "LGPL-2.1"
const SkillLicenseLGPL30 SkillLicense = "LGPL-3.0"
const SkillLicenseMIT SkillLicense = "MIT"
const SkillLicenseMPL20 SkillLicense = "MPL-2.0"
const SkillLicenseProprietary SkillLicense = "Proprietary"
const SkillLicenseUnlicense SkillLicense = "Unlicense"

type Spec struct {
	// Acronyms corresponds to the JSON schema field "acronyms".
	Acronyms []string `json:"acronyms,omitempty,omitzero" yaml:"acronyms,omitempty" mapstructure:"acronyms,omitempty"`

	// Agent corresponds to the JSON schema field "agent".
	Agent *Agent `json:"agent,omitempty,omitzero" yaml:"agent,omitempty" mapstructure:"agent,omitempty"`

	// Artifacts corresponds to the JSON schema field "artifacts".
	Artifacts *ArtifactsConfig `json:"artifacts,omitempty,omitzero" yaml:"artifacts,omitempty" mapstructure:"artifacts,omitempty"`

	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities Capabilities `json:"capabilities" yaml:"capabilities" mapstructure:"capabilities"`

	// Card corresponds to the JSON schema field "card".
	Card *Card `json:"card,omitempty,omitzero" yaml:"card,omitempty" mapstructure:"card,omitempty"`

	// Config corresponds to the JSON schema field "config".
	Config SpecConfig `json:"config,omitempty,omitzero" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// Deployment corresponds to the JSON schema field "deployment".
	Deployment *DeploymentConfig `json:"deployment,omitempty,omitzero" yaml:"deployment,omitempty" mapstructure:"deployment,omitempty"`

	// Development corresponds to the JSON schema field "development".
	Development *DevelopmentConfig `json:"development,omitempty,omitzero" yaml:"development,omitempty" mapstructure:"development,omitempty"`

	// Hooks corresponds to the JSON schema field "hooks".
	Hooks *Hooks `json:"hooks,omitempty,omitzero" yaml:"hooks,omitempty" mapstructure:"hooks,omitempty"`

	// Language corresponds to the JSON schema field "language".
	Language Language `json:"language" yaml:"language" mapstructure:"language"`

	// SCM corresponds to the JSON schema field "scm".
	SCM *SCM `json:"scm,omitempty,omitzero" yaml:"scm,omitempty" mapstructure:"scm,omitempty"`

	// Server corresponds to the JSON schema field "server".
	Server Server `json:"server" yaml:"server" mapstructure:"server"`

	// Services corresponds to the JSON schema field "services".
	Services SpecServices `json:"services,omitempty,omitzero" yaml:"services,omitempty" mapstructure:"services,omitempty"`

	// Skills corresponds to the JSON schema field "skills".
	Skills []Skill `json:"skills,omitempty,omitzero" yaml:"skills,omitempty" mapstructure:"skills,omitempty"`

	// Telemetry corresponds to the JSON schema field "telemetry".
	Telemetry *TelemetryConfig `json:"telemetry,omitempty,omitzero" yaml:"telemetry,omitempty" mapstructure:"telemetry,omitempty"`

	// Tools corresponds to the JSON schema field "tools".
	Tools []Tool `json:"tools,omitempty,omitzero" yaml:"tools,omitempty" mapstructure:"tools,omitempty"`
}

type SpecConfig map[string]map[string]any

type SpecServices map[string]Service

// Toggles OpenTelemetry instrumentation for the generated agent. When enabled, the
// consumer (e.g. adl-cli) pulls OpenTelemetry dependencies into the project,
// instruments the built-in tool calls with spans, and turns on the ADK's
// telemetry/metrics server (the A2A_TELEMETRY_ENABLE switch) so traces, metrics,
// and logs can be exported. As with spec.artifacts the schema deliberately exposes
// only the on/off switch; the exporter endpoint, metrics port, and sampling are
// resolved by the consumer and the runtime environment rather than pinned in the
// manifest. Telemetry is disabled by default - omit the block or set 'enabled:
// false' to keep it off.
type TelemetryConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

// Function-call entrypoint the agent can invoke. Generated as code in the target
// language. User-defined tools require name, description, tags, and schema;
// reserved built-in IDs (e.g. read, bash, write, edit) may omit them and have
// those fields supplied by the generator.
type Tool struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id" mapstructure:"id"`

	// Inject corresponds to the JSON schema field "inject".
	Inject []string `json:"inject,omitempty,omitzero" yaml:"inject,omitempty" mapstructure:"inject,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Free-form JSON Schema describing the tool's input parameters.
	Schema ToolSchema `json:"schema,omitempty,omitzero" yaml:"schema,omitempty" mapstructure:"schema,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`
}

// Free-form JSON Schema describing the tool's input parameters.
type ToolSchema map[string]any

type TypeScriptConfig struct {
	// NodeVersion corresponds to the JSON schema field "nodeVersion".
	NodeVersion string `json:"nodeVersion" yaml:"nodeVersion" mapstructure:"nodeVersion"`

	// PackageName corresponds to the JSON schema field "packageName".
	PackageName string `json:"packageName" yaml:"packageName" mapstructure:"packageName"`

	// Vendor corresponds to the JSON schema field "vendor".
	Vendor *VendorConfig `json:"vendor,omitempty,omitzero" yaml:"vendor,omitempty" mapstructure:"vendor,omitempty"`
}

// Extra packages to vendor into the generated project on top of whatever the
// generator pulls in by default. Use 'deps' for runtime/production dependencies
// and 'devdeps' for development- or test-only dependencies (linters, test
// frameworks, mock generators, etc.). Each entry follows the '<package>@<version>'
// form using the target language's native package and version syntax (e.g.
// 'github.com/stretchr/testify@v1.9.0' for Go, 'vitest@1.6.0' or
// '@types/node@20.11.0' for TypeScript, 'tokio@1.36.0' for Rust). Consumers are
// responsible for translating these into the language's lockfile / manifest
// format.
type VendorConfig struct {
	// Runtime/production dependencies to add to the generated project, each in
	// '<package>@<version>' form.
	Deps []string `json:"deps,omitempty,omitzero" yaml:"deps,omitempty" mapstructure:"deps,omitempty"`

	// Development- and test-only dependencies to add to the generated project (e.g.
	// testing libraries, linters, mock generators), each in '<package>@<version>'
	// form.
	Devdeps []string `json:"devdeps,omitempty,omitzero" yaml:"devdeps,omitempty" mapstructure:"devdeps,omitempty"`
}

// Configuration for deploying to Vercel. Unlike kubernetes/cloudrun which deploy
// prebuilt container images, Vercel deploys from source via its own build
// pipeline.
type VercelConfig struct {
	// Environment variables injected into the Vercel deployment. Values can use the
	// ${VAR} placeholder convention for secrets; never inline a real secret here. See
	// docs/reference/secrets.md.
	Environment VercelConfigEnvironment `json:"environment,omitempty,omitzero" yaml:"environment,omitempty" mapstructure:"environment,omitempty"`

	// Vercel framework identifier (e.g. "nextjs", "nuxtjs"). When omitted Vercel
	// auto-detects.
	Framework string `json:"framework,omitempty,omitzero" yaml:"framework,omitempty" mapstructure:"framework,omitempty"`

	// Configuration for Vercel serverless functions.
	Functions *VercelConfigFunctions `json:"functions,omitempty,omitzero" yaml:"functions,omitempty" mapstructure:"functions,omitempty"`

	// Vercel project name.
	Project string `json:"project,omitempty,omitzero" yaml:"project,omitempty" mapstructure:"project,omitempty"`

	// Vercel region identifiers where the function is deployed (e.g. "iad1", "gru1",
	// "hkg1"). Omitting lets Vercel decide.
	Regions []string `json:"regions,omitempty,omitzero" yaml:"regions,omitempty" mapstructure:"regions,omitempty"`

	// Vercel function runtime. "nodejs" for the serverless Node.js runtime (supports
	// full Node API); "edge" for the Edge runtime (limited API, runs in V8 isolates
	// at the edge).
	Runtime VercelConfigRuntime `json:"runtime,omitempty,omitzero" yaml:"runtime,omitempty" mapstructure:"runtime,omitempty"`

	// Vercel team ID or slug the project belongs to.
	Team string `json:"team,omitempty,omitzero" yaml:"team,omitempty" mapstructure:"team,omitempty"`
}

// Environment variables injected into the Vercel deployment. Values can use the
// ${VAR} placeholder convention for secrets; never inline a real secret here. See
// docs/reference/secrets.md.
type VercelConfigEnvironment map[string]string

// Configuration for Vercel serverless functions.
type VercelConfigFunctions struct {
	// Maximum function execution time in seconds.
	MaxDuration int `json:"maxDuration,omitempty,omitzero" yaml:"maxDuration,omitempty" mapstructure:"maxDuration,omitempty"`

	// Memory limit in MB (e.g. 1024).
	Memory int `json:"memory,omitempty,omitzero" yaml:"memory,omitempty" mapstructure:"memory,omitempty"`
}

type VercelConfigRuntime string

const VercelConfigRuntimeEdge VercelConfigRuntime = "edge"
const VercelConfigRuntimeNodejs VercelConfigRuntime = "nodejs"
