// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

// JSON Schema for Agent Definition Language manifests (apiVersion
// adl.inference-gateway.com/v1).
type ADL struct {
	// APIVersion corresponds to the JSON schema field "apiVersion".
	APIVersion string `json:"apiVersion" yaml:"apiVersion" mapstructure:"apiVersion"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Metadata corresponds to the JSON schema field "metadata".
	Metadata Metadata `json:"metadata" yaml:"metadata" mapstructure:"metadata"`

	// Spec corresponds to the JSON schema field "spec".
	Spec Spec `json:"spec" yaml:"spec" mapstructure:"spec"`
}

// Configures generation of AI-assistant documentation (CLAUDE.md, AGENTS.md) and
// provisioning of coding agents (Claude Code, Codex, Gemini, OpenCode, Infer, ...)
// inside sandbox environments. Each coding agent is toggled independently via its
// own subsection; by default every agent is disabled.
type AIConfig struct {
	// Claudecode corresponds to the JSON schema field "claudecode".
	Claudecode *ClaudeCodeConfig `json:"claudecode,omitempty,omitzero" yaml:"claudecode,omitempty" mapstructure:"claudecode,omitempty"`

	// Codex corresponds to the JSON schema field "codex".
	Codex *CodexConfig `json:"codex,omitempty,omitzero" yaml:"codex,omitempty" mapstructure:"codex,omitempty"`

	// Gemini corresponds to the JSON schema field "gemini".
	Gemini *GeminiConfig `json:"gemini,omitempty,omitzero" yaml:"gemini,omitempty" mapstructure:"gemini,omitempty"`

	// Infer corresponds to the JSON schema field "infer".
	Infer *InferConfig `json:"infer,omitempty,omitzero" yaml:"infer,omitempty" mapstructure:"infer,omitempty"`

	// Opencode corresponds to the JSON schema field "opencode".
	Opencode *OpenCodeConfig `json:"opencode,omitempty,omitzero" yaml:"opencode,omitempty" mapstructure:"opencode,omitempty"`
}

type Agent struct {
	// MaxTokens corresponds to the JSON schema field "maxTokens".
	MaxTokens int `json:"maxTokens,omitempty,omitzero" yaml:"maxTokens,omitempty" mapstructure:"maxTokens,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model string `json:"model,omitempty,omitzero" yaml:"model,omitempty" mapstructure:"model,omitempty"`

	// Provider corresponds to the JSON schema field "provider".
	Provider AgentProvider `json:"provider,omitempty,omitzero" yaml:"provider,omitempty" mapstructure:"provider,omitempty"`

	// SystemPrompt corresponds to the JSON schema field "systemPrompt".
	SystemPrompt string `json:"systemPrompt,omitempty,omitzero" yaml:"systemPrompt,omitempty" mapstructure:"systemPrompt,omitempty"`

	// Temperature corresponds to the JSON schema field "temperature".
	Temperature float64 `json:"temperature,omitempty,omitzero" yaml:"temperature,omitempty" mapstructure:"temperature,omitempty"`
}

type AgentProvider string

const AgentProviderAnthropic AgentProvider = "anthropic"
const AgentProviderBlank AgentProvider = ""
const AgentProviderDeepseek AgentProvider = "deepseek"
const AgentProviderGoogle AgentProvider = "google"
const AgentProviderGroq AgentProvider = "groq"
const AgentProviderMistral AgentProvider = "mistral"
const AgentProviderOllama AgentProvider = "ollama"
const AgentProviderOpenai AgentProvider = "openai"

type ArtifactsConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type AuthConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty,omitzero" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`
}

type Capabilities struct {
	// PushNotifications corresponds to the JSON schema field "pushNotifications".
	PushNotifications bool `json:"pushNotifications" yaml:"pushNotifications" mapstructure:"pushNotifications"`

	// StateTransitionHistory corresponds to the JSON schema field
	// "stateTransitionHistory".
	StateTransitionHistory bool `json:"stateTransitionHistory" yaml:"stateTransitionHistory" mapstructure:"stateTransitionHistory"`

	// Streaming corresponds to the JSON schema field "streaming".
	Streaming bool `json:"streaming" yaml:"streaming" mapstructure:"streaming"`
}

type Card struct {
	// DefaultInputModes corresponds to the JSON schema field "defaultInputModes".
	DefaultInputModes []string `json:"defaultInputModes,omitempty,omitzero" yaml:"defaultInputModes,omitempty" mapstructure:"defaultInputModes,omitempty"`

	// DefaultOutputModes corresponds to the JSON schema field "defaultOutputModes".
	DefaultOutputModes []string `json:"defaultOutputModes,omitempty,omitzero" yaml:"defaultOutputModes,omitempty" mapstructure:"defaultOutputModes,omitempty"`

	// DocumentationURL corresponds to the JSON schema field "documentationUrl".
	DocumentationURL string `json:"documentationUrl,omitempty,omitzero" yaml:"documentationUrl,omitempty" mapstructure:"documentationUrl,omitempty"`

	// IconURL corresponds to the JSON schema field "iconUrl".
	IconURL string `json:"iconUrl,omitempty,omitzero" yaml:"iconUrl,omitempty" mapstructure:"iconUrl,omitempty"`

	// PreferredTransport corresponds to the JSON schema field "preferredTransport".
	PreferredTransport string `json:"preferredTransport,omitempty,omitzero" yaml:"preferredTransport,omitempty" mapstructure:"preferredTransport,omitempty"`

	// ProtocolVersion corresponds to the JSON schema field "protocolVersion".
	ProtocolVersion string `json:"protocolVersion,omitempty,omitzero" yaml:"protocolVersion,omitempty" mapstructure:"protocolVersion,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

// Provision Anthropic's Claude Code coding agent inside the sandbox.
type ClaudeCodeConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type CloudRunConfig struct {
	// Environment corresponds to the JSON schema field "environment".
	Environment CloudRunConfigEnvironment `json:"environment,omitempty,omitzero" yaml:"environment,omitempty" mapstructure:"environment,omitempty"`

	// Image corresponds to the JSON schema field "image".
	Image *ImageConfig `json:"image,omitempty,omitzero" yaml:"image,omitempty" mapstructure:"image,omitempty"`

	// Resources corresponds to the JSON schema field "resources".
	Resources *ResourcesConfig `json:"resources,omitempty,omitzero" yaml:"resources,omitempty" mapstructure:"resources,omitempty"`

	// Scaling corresponds to the JSON schema field "scaling".
	Scaling *ScalingConfig `json:"scaling,omitempty,omitzero" yaml:"scaling,omitempty" mapstructure:"scaling,omitempty"`

	// Service corresponds to the JSON schema field "service".
	Service *ServiceConfig `json:"service,omitempty,omitzero" yaml:"service,omitempty" mapstructure:"service,omitempty"`
}

type CloudRunConfigEnvironment map[string]string

// Provision OpenAI's Codex coding agent inside the sandbox.
type CodexConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type DeploymentConfig struct {
	// CloudRun corresponds to the JSON schema field "cloudrun".
	CloudRun *CloudRunConfig `json:"cloudrun,omitempty,omitzero" yaml:"cloudrun,omitempty" mapstructure:"cloudrun,omitempty"`

	// Kubernetes corresponds to the JSON schema field "kubernetes".
	Kubernetes *KubernetesConfig `json:"kubernetes,omitempty,omitzero" yaml:"kubernetes,omitempty" mapstructure:"kubernetes,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type DeploymentConfigType `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

type DeploymentConfigType string

const DeploymentConfigTypeCloudRun DeploymentConfigType = "cloudrun"
const DeploymentConfigTypeKubernetes DeploymentConfigType = "kubernetes"

type DevContainerConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

// Local development experience for the agent: sandboxed dev environments (flox,
// devcontainer, dockerCompose), AI-assistant integration (CLAUDE.md/AGENTS.md
// generation, claude-code provisioning), and extra sandbox-level dependencies
// (deps) for tools that don't belong to any single language's package manager
// (e.g. deno, kubectl, terraform).
type DevelopmentConfig struct {
	// AI corresponds to the JSON schema field "ai".
	AI *AIConfig `json:"ai,omitempty,omitzero" yaml:"ai,omitempty" mapstructure:"ai,omitempty"`

	// Extra packages to install into the development sandbox (flox, devcontainer,
	// dockerCompose) on top of whatever the generator pulls in by default. Use this
	// for cross-cutting tools that aren't tied to one of the project's languages -
	// e.g. 'deno@2.1.4', 'kubectl@1.31.0', 'terraform@1.9.5'. Each entry follows the
	// '<package>@<version>' form; consumers are responsible for resolving the package
	// against the sandbox's native package source (Nixpkgs for flox, apt/apk/feature
	// for devcontainer, image layers for dockerCompose).
	Deps []string `json:"deps,omitempty,omitzero" yaml:"deps,omitempty" mapstructure:"deps,omitempty"`

	// Sandbox corresponds to the JSON schema field "sandbox".
	Sandbox *SandboxConfig `json:"sandbox,omitempty,omitzero" yaml:"sandbox,omitempty" mapstructure:"sandbox,omitempty"`
}

type DockerComposeConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type FloxConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

// Provision Google's Gemini coding agent inside the sandbox.
type GeminiConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type GoConfig struct {
	// Module corresponds to the JSON schema field "module".
	Module string `json:"module" yaml:"module" mapstructure:"module"`

	// Vendor corresponds to the JSON schema field "vendor".
	Vendor *VendorConfig `json:"vendor,omitempty,omitzero" yaml:"vendor,omitempty" mapstructure:"vendor,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

type Hooks struct {
	// Post corresponds to the JSON schema field "post".
	Post []string `json:"post,omitempty,omitzero" yaml:"post,omitempty" mapstructure:"post,omitempty"`
}

type ImageConfig struct {
	// Registry corresponds to the JSON schema field "registry".
	Registry string `json:"registry,omitempty,omitzero" yaml:"registry,omitempty" mapstructure:"registry,omitempty"`

	// Repository corresponds to the JSON schema field "repository".
	Repository string `json:"repository,omitempty,omitzero" yaml:"repository,omitempty" mapstructure:"repository,omitempty"`

	// Tag corresponds to the JSON schema field "tag".
	Tag string `json:"tag,omitempty,omitzero" yaml:"tag,omitempty" mapstructure:"tag,omitempty"`

	// UseCloudBuild corresponds to the JSON schema field "useCloudBuild".
	UseCloudBuild bool `json:"useCloudBuild,omitempty,omitzero" yaml:"useCloudBuild,omitempty" mapstructure:"useCloudBuild,omitempty"`
}

// Provision the Inference Gateway 'infer' coding agent inside the sandbox.
type InferConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type KubernetesConfig struct {
	// Image corresponds to the JSON schema field "image".
	Image *ImageConfig `json:"image,omitempty,omitzero" yaml:"image,omitempty" mapstructure:"image,omitempty"`
}

type Language struct {
	// Go corresponds to the JSON schema field "go".
	Go *GoConfig `json:"go,omitempty,omitzero" yaml:"go,omitempty" mapstructure:"go,omitempty"`

	// Rust corresponds to the JSON schema field "rust".
	Rust *RustConfig `json:"rust,omitempty,omitzero" yaml:"rust,omitempty" mapstructure:"rust,omitempty"`

	// TypeScript corresponds to the JSON schema field "typescript".
	TypeScript *TypeScriptConfig `json:"typescript,omitempty,omitzero" yaml:"typescript,omitempty" mapstructure:"typescript,omitempty"`
}

type Metadata struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

// Provision the OpenCode coding agent inside the sandbox.
type OpenCodeConfig struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type ResourcesConfig struct {
	// CPU corresponds to the JSON schema field "cpu".
	CPU string `json:"cpu,omitempty,omitzero" yaml:"cpu,omitempty" mapstructure:"cpu,omitempty"`

	// Memory corresponds to the JSON schema field "memory".
	Memory string `json:"memory,omitempty,omitzero" yaml:"memory,omitempty" mapstructure:"memory,omitempty"`
}

type RustConfig struct {
	// Edition corresponds to the JSON schema field "edition".
	Edition string `json:"edition" yaml:"edition" mapstructure:"edition"`

	// Features corresponds to the JSON schema field "features".
	Features []string `json:"features,omitempty,omitzero" yaml:"features,omitempty" mapstructure:"features,omitempty"`

	// PackageName corresponds to the JSON schema field "packageName".
	PackageName string `json:"packageName" yaml:"packageName" mapstructure:"packageName"`

	// Vendor corresponds to the JSON schema field "vendor".
	Vendor *VendorConfig `json:"vendor,omitempty,omitzero" yaml:"vendor,omitempty" mapstructure:"vendor,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

type SCM struct {
	// CD corresponds to the JSON schema field "cd".
	CD bool `json:"cd,omitempty,omitzero" yaml:"cd,omitempty" mapstructure:"cd,omitempty"`

	// CI corresponds to the JSON schema field "ci".
	CI bool `json:"ci,omitempty,omitzero" yaml:"ci,omitempty" mapstructure:"ci,omitempty"`

	// Dependabot corresponds to the JSON schema field "dependabot".
	Dependabot bool `json:"dependabot,omitempty,omitzero" yaml:"dependabot,omitempty" mapstructure:"dependabot,omitempty"`

	// GithubApp corresponds to the JSON schema field "github_app".
	GithubApp bool `json:"github_app,omitempty,omitzero" yaml:"github_app,omitempty" mapstructure:"github_app,omitempty"`

	// IssueTemplates corresponds to the JSON schema field "issue_templates".
	IssueTemplates bool `json:"issue_templates,omitempty,omitzero" yaml:"issue_templates,omitempty" mapstructure:"issue_templates,omitempty"`

	// Provider corresponds to the JSON schema field "provider".
	Provider SCMProvider `json:"provider,omitempty,omitzero" yaml:"provider,omitempty" mapstructure:"provider,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type SCMProvider string

const SCMProviderBitbucket SCMProvider = "bitbucket"
const SCMProviderGithub SCMProvider = "github"
const SCMProviderGitlab SCMProvider = "gitlab"

// Reproducible development environments. flox, devcontainer, and dockerCompose are
// alternative ways to package the same sandbox; pick what suits the team.
type SandboxConfig struct {
	// DevContainer corresponds to the JSON schema field "devcontainer".
	DevContainer *DevContainerConfig `json:"devcontainer,omitempty,omitzero" yaml:"devcontainer,omitempty" mapstructure:"devcontainer,omitempty"`

	// DockerCompose corresponds to the JSON schema field "dockerCompose".
	DockerCompose *DockerComposeConfig `json:"dockerCompose,omitempty,omitzero" yaml:"dockerCompose,omitempty" mapstructure:"dockerCompose,omitempty"`

	// Flox corresponds to the JSON schema field "flox".
	Flox *FloxConfig `json:"flox,omitempty,omitzero" yaml:"flox,omitempty" mapstructure:"flox,omitempty"`
}

type ScalingConfig struct {
	// Concurrency corresponds to the JSON schema field "concurrency".
	Concurrency int `json:"concurrency,omitempty,omitzero" yaml:"concurrency,omitempty" mapstructure:"concurrency,omitempty"`

	// MaxInstances corresponds to the JSON schema field "maxInstances".
	MaxInstances int `json:"maxInstances,omitempty,omitzero" yaml:"maxInstances,omitempty" mapstructure:"maxInstances,omitempty"`

	// MinInstances corresponds to the JSON schema field "minInstances".
	MinInstances int `json:"minInstances,omitempty,omitzero" yaml:"minInstances,omitempty" mapstructure:"minInstances,omitempty"`
}

type Server struct {
	// Auth corresponds to the JSON schema field "auth".
	Auth *AuthConfig `json:"auth,omitempty,omitzero" yaml:"auth,omitempty" mapstructure:"auth,omitempty"`

	// Debug corresponds to the JSON schema field "debug".
	Debug bool `json:"debug,omitempty,omitzero" yaml:"debug,omitempty" mapstructure:"debug,omitempty"`

	// Port corresponds to the JSON schema field "port".
	Port int `json:"port" yaml:"port" mapstructure:"port"`

	// Scheme corresponds to the JSON schema field "scheme".
	Scheme string `json:"scheme,omitempty,omitzero" yaml:"scheme,omitempty" mapstructure:"scheme,omitempty"`
}

type Service struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Factory corresponds to the JSON schema field "factory".
	Factory string `json:"factory" yaml:"factory" mapstructure:"factory"`

	// Interface corresponds to the JSON schema field "interface".
	Interface string `json:"interface" yaml:"interface" mapstructure:"interface"`

	// Type corresponds to the JSON schema field "type".
	Type ServiceType `json:"type" yaml:"type" mapstructure:"type"`
}

type ServiceConfig struct {
	// AllowUnauthenticated corresponds to the JSON schema field
	// "allowUnauthenticated".
	AllowUnauthenticated bool `json:"allowUnauthenticated,omitempty,omitzero" yaml:"allowUnauthenticated,omitempty" mapstructure:"allowUnauthenticated,omitempty"`

	// ExecutionEnvironment corresponds to the JSON schema field
	// "executionEnvironment".
	ExecutionEnvironment string `json:"executionEnvironment,omitempty,omitzero" yaml:"executionEnvironment,omitempty" mapstructure:"executionEnvironment,omitempty"`

	// ServiceAccount corresponds to the JSON schema field "serviceAccount".
	ServiceAccount string `json:"serviceAccount,omitempty,omitzero" yaml:"serviceAccount,omitempty" mapstructure:"serviceAccount,omitempty"`

	// Timeout corresponds to the JSON schema field "timeout".
	Timeout int `json:"timeout,omitempty,omitzero" yaml:"timeout,omitempty" mapstructure:"timeout,omitempty"`
}

type ServiceType string

const ServiceTypeClient ServiceType = "client"
const ServiceTypeMiddleware ServiceType = "middleware"
const ServiceTypeRepository ServiceType = "repository"
const ServiceTypeService ServiceType = "service"

// Markdown playbook injected into the agent's system prompt. Pulled from the
// skills registry or scaffolded blank with bare: true.
type Skill struct {
	// Bare corresponds to the JSON schema field "bare".
	Bare bool `json:"bare,omitempty,omitzero" yaml:"bare,omitempty" mapstructure:"bare,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id" mapstructure:"id"`

	// License under which the skill is distributed. Must be one of the accepted SPDX
	// license identifiers, or "Proprietary" for closed-source skills. Consumers
	// should mirror this value in the SKILL.md frontmatter so the licence travels
	// with the playbook; shipping a separate LICENSE file alongside SKILL.md is
	// optional and not enforced by the schema. New identifiers may be added in future
	// minor versions of the schema.
	License SkillLicense `json:"license,omitempty,omitzero" yaml:"license,omitempty" mapstructure:"license,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Source corresponds to the JSON schema field "source".
	Source string `json:"source,omitempty,omitzero" yaml:"source,omitempty" mapstructure:"source,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version,omitempty,omitzero" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

type SkillLicense string

const SkillLicenseApache20 SkillLicense = "Apache-2.0"
const SkillLicenseBSD2Clause SkillLicense = "BSD-2-Clause"
const SkillLicenseBSD3Clause SkillLicense = "BSD-3-Clause"
const SkillLicenseCC010 SkillLicense = "CC0-1.0"
const SkillLicenseCCBY40 SkillLicense = "CC-BY-4.0"
const SkillLicenseCCBYSA40 SkillLicense = "CC-BY-SA-4.0"
const SkillLicenseGPL20 SkillLicense = "GPL-2.0"
const SkillLicenseGPL30 SkillLicense = "GPL-3.0"
const SkillLicenseISC SkillLicense = "ISC"
const SkillLicenseLGPL21 SkillLicense = "LGPL-2.1"
const SkillLicenseLGPL30 SkillLicense = "LGPL-3.0"
const SkillLicenseMIT SkillLicense = "MIT"
const SkillLicenseMPL20 SkillLicense = "MPL-2.0"
const SkillLicenseProprietary SkillLicense = "Proprietary"
const SkillLicenseUnlicense SkillLicense = "Unlicense"

type Spec struct {
	// Acronyms corresponds to the JSON schema field "acronyms".
	Acronyms []string `json:"acronyms,omitempty,omitzero" yaml:"acronyms,omitempty" mapstructure:"acronyms,omitempty"`

	// Agent corresponds to the JSON schema field "agent".
	Agent *Agent `json:"agent,omitempty,omitzero" yaml:"agent,omitempty" mapstructure:"agent,omitempty"`

	// Artifacts corresponds to the JSON schema field "artifacts".
	Artifacts *ArtifactsConfig `json:"artifacts,omitempty,omitzero" yaml:"artifacts,omitempty" mapstructure:"artifacts,omitempty"`

	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities Capabilities `json:"capabilities" yaml:"capabilities" mapstructure:"capabilities"`

	// Card corresponds to the JSON schema field "card".
	Card *Card `json:"card,omitempty,omitzero" yaml:"card,omitempty" mapstructure:"card,omitempty"`

	// Config corresponds to the JSON schema field "config".
	Config SpecConfig `json:"config,omitempty,omitzero" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// Deployment corresponds to the JSON schema field "deployment".
	Deployment *DeploymentConfig `json:"deployment,omitempty,omitzero" yaml:"deployment,omitempty" mapstructure:"deployment,omitempty"`

	// Development corresponds to the JSON schema field "development".
	Development *DevelopmentConfig `json:"development,omitempty,omitzero" yaml:"development,omitempty" mapstructure:"development,omitempty"`

	// Hooks corresponds to the JSON schema field "hooks".
	Hooks *Hooks `json:"hooks,omitempty,omitzero" yaml:"hooks,omitempty" mapstructure:"hooks,omitempty"`

	// Language corresponds to the JSON schema field "language".
	Language Language `json:"language" yaml:"language" mapstructure:"language"`

	// SCM corresponds to the JSON schema field "scm".
	SCM *SCM `json:"scm,omitempty,omitzero" yaml:"scm,omitempty" mapstructure:"scm,omitempty"`

	// Server corresponds to the JSON schema field "server".
	Server Server `json:"server" yaml:"server" mapstructure:"server"`

	// Services corresponds to the JSON schema field "services".
	Services SpecServices `json:"services,omitempty,omitzero" yaml:"services,omitempty" mapstructure:"services,omitempty"`

	// Skills corresponds to the JSON schema field "skills".
	Skills []Skill `json:"skills,omitempty,omitzero" yaml:"skills,omitempty" mapstructure:"skills,omitempty"`

	// Tools corresponds to the JSON schema field "tools".
	Tools []Tool `json:"tools,omitempty,omitzero" yaml:"tools,omitempty" mapstructure:"tools,omitempty"`
}

type SpecConfig map[string]map[string]any

type SpecServices map[string]Service

// Function-call entrypoint the agent can invoke. Generated as code in the target
// language. User-defined tools require name, description, tags, and schema;
// reserved built-in IDs (e.g. read, bash, write, edit) may omit them and have
// those fields supplied by the generator.
type Tool struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id" mapstructure:"id"`

	// Inject corresponds to the JSON schema field "inject".
	Inject []string `json:"inject,omitempty,omitzero" yaml:"inject,omitempty" mapstructure:"inject,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Free-form JSON Schema describing the tool's input parameters.
	Schema ToolSchema `json:"schema,omitempty,omitzero" yaml:"schema,omitempty" mapstructure:"schema,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`
}

// Free-form JSON Schema describing the tool's input parameters.
type ToolSchema map[string]any

type TypeScriptConfig struct {
	// NodeVersion corresponds to the JSON schema field "nodeVersion".
	NodeVersion string `json:"nodeVersion" yaml:"nodeVersion" mapstructure:"nodeVersion"`

	// PackageName corresponds to the JSON schema field "packageName".
	PackageName string `json:"packageName" yaml:"packageName" mapstructure:"packageName"`

	// Vendor corresponds to the JSON schema field "vendor".
	Vendor *VendorConfig `json:"vendor,omitempty,omitzero" yaml:"vendor,omitempty" mapstructure:"vendor,omitempty"`
}

// Extra packages to vendor into the generated project on top of whatever the
// generator pulls in by default. Use 'deps' for runtime/production dependencies
// and 'devdeps' for development- or test-only dependencies (linters, test
// frameworks, mock generators, etc.). Each entry follows the '<package>@<version>'
// form using the target language's native package and version syntax (e.g.
// 'github.com/stretchr/testify@v1.9.0' for Go, 'vitest@1.6.0' or
// '@types/node@20.11.0' for TypeScript, 'tokio@1.36.0' for Rust). Consumers are
// responsible for translating these into the language's lockfile / manifest
// format.
type VendorConfig struct {
	// Runtime/production dependencies to add to the generated project, each in
	// '<package>@<version>' form.
	Deps []string `json:"deps,omitempty,omitzero" yaml:"deps,omitempty" mapstructure:"deps,omitempty"`

	// Development- and test-only dependencies to add to the generated project (e.g.
	// testing libraries, linters, mock generators), each in '<package>@<version>'
	// form.
	Devdeps []string `json:"devdeps,omitempty,omitzero" yaml:"devdeps,omitempty" mapstructure:"devdeps,omitempty"`
}
