package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	schema "github.com/inference-gateway/adl-cli/internal/schema"
)

// telemetryADL builds a minimal Go manifest with a single built-in tool. The
// no-op post hook replaces the default `go mod tidy`/`go fmt` commands so the
// test stays hermetic - it never reaches the network - while still exercising
// the full file-writing pipeline that stamps generated-code headers.
func telemetryADL(enabled bool) *schema.ADL {
	adl := &schema.ADL{
		APIVersion: "adl.inference-gateway.com/v1",
		Kind:       "Agent",
		Metadata: schema.Metadata{
			Name:        "telemetry-agent",
			Description: "tests spec.telemetry wiring",
			Version:     "1.0.0",
		},
		Spec: schema.Spec{
			Capabilities: schema.Capabilities{},
			Server:       schema.Server{Port: 8080},
			Language: schema.Language{
				Go: &schema.GoConfig{
					Module:  "github.com/example/telemetry-agent",
					Version: "1.26.2",
				},
			},
			Tools: []schema.Tool{{ID: "read"}},
			Hooks: &schema.Hooks{Post: []string{"true"}},
		},
	}
	if enabled {
		adl.Spec.Telemetry = &schema.TelemetryConfig{Enabled: true}
	}
	return adl
}

func generateTelemetryProject(t *testing.T, enabled bool) string {
	t.Helper()

	tmpDir, err := os.MkdirTemp("", "adl-telemetry-*")
	if err != nil {
		t.Fatalf("MkdirTemp: %v", err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(tmpDir) })

	adlPath := filepath.Join(tmpDir, "agent.yaml")
	writeYAML(t, adlPath, telemetryADL(enabled))

	outDir := filepath.Join(tmpDir, "out")
	gen := New(Config{Template: "minimal", Overwrite: true, Version: "test"})
	if err := gen.Generate(adlPath, outDir); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	return outDir
}

// TestGenerator_TelemetryEnabled_EndToEnd drives spec.telemetry.enabled from a
// manifest through Generate() and asserts the three on-disk effects: the shared
// span helper is emitted (carrying the DO NOT EDIT header like every generated
// file), the built-in handler calls it, and go.mod pulls in the OTel runtime.
func TestGenerator_TelemetryEnabled_EndToEnd(t *testing.T) {
	outDir := generateTelemetryProject(t, true)

	telemetryBytes, err := os.ReadFile(filepath.Join(outDir, "tools", "telemetry.go"))
	if err != nil {
		t.Fatalf("read tools/telemetry.go: %v", err)
	}
	telemetry := string(telemetryBytes)
	if !strings.HasPrefix(telemetry, "// Code generated by ADL CLI") {
		t.Errorf("tools/telemetry.go missing generated-code header:\n%s", firstLines(telemetry, 3))
	}
	if !strings.Contains(telemetry, "func startToolSpan(") {
		t.Errorf("tools/telemetry.go missing startToolSpan helper")
	}

	readBytes, err := os.ReadFile(filepath.Join(outDir, "tools", "read.go"))
	if err != nil {
		t.Fatalf("read tools/read.go: %v", err)
	}
	if !strings.Contains(string(readBytes), `startToolSpan(ctx, "read")`) {
		t.Errorf("tools/read.go missing telemetry span call")
	}

	goModBytes, err := os.ReadFile(filepath.Join(outDir, "go.mod"))
	if err != nil {
		t.Fatalf("read go.mod: %v", err)
	}
	if !strings.Contains(string(goModBytes), "go.opentelemetry.io/otel") {
		t.Errorf("go.mod missing OpenTelemetry require:\n%s", goModBytes)
	}
}

// TestGenerator_TelemetryDisabled_EndToEnd is the off-by-default guard: with no
// spec.telemetry block, none of the OpenTelemetry wiring is emitted.
func TestGenerator_TelemetryDisabled_EndToEnd(t *testing.T) {
	outDir := generateTelemetryProject(t, false)

	if _, err := os.Stat(filepath.Join(outDir, "tools", "telemetry.go")); !os.IsNotExist(err) {
		t.Errorf("tools/telemetry.go should not be generated when telemetry is off (stat err=%v)", err)
	}

	readBytes, err := os.ReadFile(filepath.Join(outDir, "tools", "read.go"))
	if err != nil {
		t.Fatalf("read tools/read.go: %v", err)
	}
	if strings.Contains(string(readBytes), "startToolSpan") {
		t.Errorf("tools/read.go should not reference startToolSpan when telemetry is off")
	}

	goModBytes, err := os.ReadFile(filepath.Join(outDir, "go.mod"))
	if err != nil {
		t.Fatalf("read go.mod: %v", err)
	}
	if strings.Contains(string(goModBytes), "go.opentelemetry.io/otel") {
		t.Errorf("go.mod should not require OpenTelemetry when telemetry is off:\n%s", goModBytes)
	}
}

func firstLines(s string, n int) string {
	lines := strings.SplitN(s, "\n", n+1)
	if len(lines) > n {
		lines = lines[:n]
	}
	return strings.Join(lines, "\n")
}
