---
name: Artifacts

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  security-events: write
  id-token: write

jobs:
  upload_artifacts:
    name: Upload Artifacts
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: '1.24'
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
        with:
          version: latest

      - name: Install GoReleaser
        run: |
          curl -sSL https://github.com/goreleaser/goreleaser/releases/download/v2.7.0/goreleaser_Linux_x86_64.tar.gz | tar -xzv -C /usr/local/bin goreleaser

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        run: |
          goreleaser release --clean

      - name: Upload Artifacts to Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          for file in dist/a2a_*; do
            if [ -d "$file" ]; then
              echo "Skipping directory: $file"
              continue
            fi
            
            echo "Uploading $file to release ${{ env.VERSION }}"
            gh release upload ${{ env.VERSION }} "$file" --clobber
          done

          if [ -f "dist/checksums.txt" ]; then
            gh release upload ${{ env.VERSION }} "dist/checksums.txt" --clobber
          fi
