name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: '1.24'
          cache: true

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v2.1.6

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 'lts/*'

      - name: Tidy Go modules
        run: find . -name 'go.mod' -execdir go mod tidy \;

      - name: Check dirty
        run: git diff --exit-code

      - name: Run Lint
        run: golangci-lint run

      - name: Build
        run: go build .

      - name: Test
        run: go test -v ./...
